
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Adminlogin extends javax.swing.JFrame {
    public int z=0;

    /**
     * Creates new form Adminlogin
     */
    public Adminlogin() {
        initComponents();
        addbtn.setVisible(false);
        updatebtn.setVisible(false);
        orderbtn.setVisible(false);
        membtn.setVisible(false);
        feedbackbtn.setVisible(false);
        logoutbtn.setVisible(false);
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel10.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        orderbtn = new javax.swing.JButton();
        membtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        feedbackbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(90, 20));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control hide and show.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 67, -1, -1));

        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new product.png"))); // NOI18N
        addbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addbtnComponentShown(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        orderbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details product.png"))); // NOI18N
        orderbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                orderbtnComponentShown(evt);
            }
        });
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        membtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        membtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                membtnComponentShown(evt);
            }
        });
        membtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membtnActionPerformed(evt);
            }
        });
        getContentPane().add(membtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update product.png"))); // NOI18N
        updatebtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updatebtnComponentShown(evt);
            }
        });
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        feedbackbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyer.png"))); // NOI18N
        feedbackbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                feedbackbtnComponentShown(evt);
            }
        });
        feedbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(feedbackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logoutbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutbtnComponentShown(evt);
            }
        });
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tamil INetFont", 1, 18)); // NOI18N
        jLabel1.setText("Admin ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Pizza");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Pizza");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Member");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Feedback");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Close");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 150, 43, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton2ComponentShown(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza-gbe69d3505_1280.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int a = JOptionPane.showConfirmDialog(null, "Do you want to close","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
           System.exit(0);
         
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
       int a=JOptionPane.showConfirmDialog(null, "Do you want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
           setVisible(false);
           new Admin().setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(z==0)
        {
            try{
            Thread.sleep(250);
            addbtn.setVisible(true);
            jLabel2.setVisible(true);
            }
            catch(Exception e)
            {
                
            }
        }
        else
        {
           addbtn.setVisible(false);
        updatebtn.setVisible(false);
        orderbtn.setVisible(false);
        membtn.setVisible(false);
        feedbackbtn.setVisible(false);
        logoutbtn.setVisible(false);
        jButton2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel10.setVisible(false);
        z=0;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void addbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addbtnComponentShown
        try{
            Thread.sleep(250);
            updatebtn.setVisible(true);
            jLabel3.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_addbtnComponentShown

    private void updatebtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updatebtnComponentShown
        try{
            Thread.sleep(250);
            orderbtn.setVisible(true);
            jLabel4.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_updatebtnComponentShown

    private void orderbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_orderbtnComponentShown
        try{
            Thread.sleep(250);
            membtn.setVisible(true);
            jLabel5.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_orderbtnComponentShown

    private void membtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_membtnComponentShown
       try{
            Thread.sleep(250);
            feedbackbtn.setVisible(true);
            jLabel6.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_membtnComponentShown

    private void feedbackbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_feedbackbtnComponentShown
        try{
            Thread.sleep(250);
            logoutbtn.setVisible(true);
            jLabel7.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_feedbackbtnComponentShown

    private void logoutbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutbtnComponentShown
        try{
            Thread.sleep(250);
            jButton2.setVisible(true);
            jLabel10.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_logoutbtnComponentShown

    private void jButton2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ComponentShown

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
       new Addpizza().setVisible(true);
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        new Updatepizza().setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed
        new orderdpizza().setVisible(true);
    }//GEN-LAST:event_orderbtnActionPerformed

    private void membtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membtnActionPerformed
        new edmember().setVisible(true);
    }//GEN-LAST:event_membtnActionPerformed

    private void feedbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackbtnActionPerformed
        new feedback().setVisible(true);
    }//GEN-LAST:event_feedbackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton feedbackbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton membtn;
    private javax.swing.JButton orderbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
